version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine3.21
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: password123 # Just for fun
      - MYSQL_DATABASE: users
      - MYSQL_USER: root
      - MYSQL_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_ENV: development
      - MYSQL_HOST: db
      - MYSQL_USER: root
      - MYSQL_PASSWORD: password123
      - MYSQL_DB: users
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  db_data:
